### PR TITLE
Windows users should install to texmf.

### PR DESCRIPTION
**Pull request by RomanLangrehr**

### CODE REVIEW

**Comment by jGleitz** [comment]
The path given worked for `sdqthesis.cls` (without having to change settings)
- Is there any reason why it should work for `sdqthesis.cls` but not for the KIT `.sty` files?
- I think we should handle this uniformly

**Comment by RomanLangrehr** [comment]
The sdq-Thesis class should be in texmf, too. On my machine it is installed in texmf.

**Comment by jGleitz** [comment]
> On my machine it is installed in texmf

I think that creating a custom `texmf` root might be a more “elegant” solution. But `C:\Program Files (x86)\MiKTeX 2.9\tex\latex\misc\` seems to be a valid texmf tree, too. The latter does not need additional setup, though.

**Comment by RomanLangrehr** [comment]
Yes, but in this tree MixTeX installs it classes and I don't think you should get them mixed up.

**Comment by jGleitz** [comment]
I see. Could you then please add instructions on how to add a user-specific `texmf` tree? I don’t think we can assume everybody knows how to do that (yes they could google it, but this guide is meant to get you started as soon as possible).

**Comment by RomanLangrehr** [comment]
Its in the description, you just need to add the root in MixTex settings.

And I don't think everybody has to install it like this, but I think we should write the proper way in our documentation.

**Comment by jGleitz** [comment]
>  I think we should write the proper way in our documentation.

Absolutely. Thanks for pointing out!

I will close this PR because I want to add some more words about this (like giving the user a path he should use). Please see my original PR and verify it’s okay.

**Comment by jGleitz** [comment]
But if `[texmf]` is my local root like I added it in the MiKTeX settings, the files must still go to `[texmf]\tex\latex\KIT`, don’t they?

**Comment by RomanLangrehr** [comment]
> But if [texmf] is my local root like I added it in the MiKTeX settings, the files must still go to [texmf]\tex\latex\KIT, don’t they?

Yes.

**Pull request closed without merging**
